name: lazy_engineer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  lottie: ^1.3.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  flutter_staggered_grid_view: ^0.6.2

  ### logic
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5

  ### network
  dio: ^4.0.6
  build_runner: ^2.2.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: 2.1.0+1
  url_strategy: ^0.2.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
