name: lazy_engineer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  file_picker: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.4
  freezed_annotation: ^2.0.3
  go_router: ^5.1.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  json_annotation: ^4.7.0
  lottie: ^1.3.0
  open_app_file: ^4.0.1
  path_provider: ^2.0.11
  pdf_thumbnail: ^0.1.5+1
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  sqflite: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  json_serializable: ^6.4.1
  lint: ^2.0.1
  retrofit_generator: ^4.1.0+1
  url_strategy: ^0.2.0
  hive_generator: 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
